title: Elwyn Calendar
author: Chuck Wojciuk
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Site to show progress on the Elwyn calendar Development

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
